### ISSUE TITLE
Range setting via web interface has no effect

### ISSUE THREAD

**Issue by ubx** [roema/Open-Glider-Network-Groundstation#13]
Hi Manuel

It always keeps the value 100. Maybe related to #11 ?
Andreas

**Comment by roema** [comment]
Thanks Andreas! I have found the bug!

Manu

**Comment by roema** [comment]
Hi Andreas!

Fixed in new version. I will send you  an image for testing.

**Comment by CazYokoyama** [comment]
fixed on 0.1.0-18 while version number is still -17.

**Comment by roema** [comment]
I have installed the new firmware and it shows -18 in version. What do you mean?

**Comment by ubx** [comment]
Tested with version 0.1.0-18, it works.

Thanks Manuel!

**Comment by CazYokoyama** [comment]
> I have installed the new firmware and it shows -18 in version. What do you mean?
I build the image from 0.1.0-18 tag which you don't update version.h.
