### ISSUE TITLE
Zabbix config

### ISSUE THREAD

**Issue by JacquesGr** [roema/Open-Glider-Network-Groundstation#16]
For the Zabbix monitoring

I assume we create a file called zabbix.txt with:
xxx.xxx.xxx.xxx (IP of zabbix server)
10051
ogn_base

Where do we save the file?
I tried to upload it via the OGNBS gui but I dont see any traffic hitting my zabbix server

Also in the case above, is ogn_base the key?

Thanks

**Comment by roema** [comment]
Hi Jaq!
In new version, use config.json. There is a section with zabbix.
I have forgotten to update the readme, now its correct, please excuse me!

At the moment, its very rudimentary. 
The beam is sending zabbix traps **without encryption**!

ogn_base is the name of the device in zabbix server. Configure the device.type as zabbix trapper and create items like battery voltage.

I've attached a few screenshots for you. 
If you have any questions, please let me know at any time!!!

![device](https://user-images.githubusercontent.com/9306994/112790344-6e321180-905f-11eb-8971-6566362897d2.png)
![Items](https://user-images.githubusercontent.com/9306994/112790377-80ac4b00-905f-11eb-88af-f6e4287faf19.png)
![Trapper](https://user-images.githubusercontent.com/9306994/112790387-86099580-905f-11eb-8a5d-60159e106e79.png)

**Comment by roema** [comment]
Sorry for the delay. I will test Zabbix feature this weekend!

**Comment by roema** [comment]
Use config.json to configure zabbix values.
Make sure your server is pingable.
