### ISSUE TITLE
Lon of "OGN Ground Station" is blank when lon is negative 

### ISSUE THREAD

**Issue by CazYokoyama** [roema/Open-Glider-Network-Groundstation#20]
When config.json has 

   "coordinates":{
      "lon":-122.84105,

, i.e. negative value, the web site, "OGN Ground Station" shows blank on Lon.

![Screenshot from 2021-05-09 12-20-26](https://user-images.githubusercontent.com/2885042/117584314-16a4ae00-b0c1-11eb-9660-860150ea12e1.png)

**Comment by roema** [comment]
Hi Caz!

Sorry for the delay!
Please check latest version and close issue if fixes
