### ISSUE TITLE
  saving is not possible

### ISSUE THREAD

**Issue by hem0773** [roema/Open-Glider-Network-Groundstation#21]
if you click on the "save button", the data is lost and the "old" start page appears where you only had to download the files

My board is V1.1
![grafik](https://user-images.githubusercontent.com/57199067/125657125-89250fac-e84d-4e8e-8791-7b039a65c58d.png)

**Comment by roema** [comment]
Hi @hem0773 !

Thanks for you issue!
The last few weeks i was a bit stressed, so i couldn't do anything for a longer period of time. From month on I have more time for the project. I will look into the problem. 

Thanks for your patience!

Manu

**Comment by hem0773** [comment]
OK thanks
But no data is received

What am I doing wrong

![grafik](https://user-images.githubusercontent.com/57199067/126353478-afe2753b-035b-431e-bbb1-6044a6117e44.png)

**Comment by roema** [comment]
should be fixed in latest version 0.1.0-21

Thanks to Nick.
