### ISSUE TITLE
multiple APs are defined

### ISSUE THREAD

**Issue by CazYokoyama** [roema/Open-Glider-Network-Groundstation#28]
5 APs are defined by the following code.
String ogn_ssid[5];
String ogn_wpass[5];

@roema Do you expect only one AP and don't want to accept multiple APs? If so, you may define them as not an array. If you want to accept multiple APs. I'll make a patch.

**Comment by roema** [comment]
Hello @caz! Multiple APs are supported. You have to enter it in config.json. Only the first SSID is used in the web interface.
```
{
   "wifi":{
      "ssid":[
         "ssid",
         "xxxxxxx",
         "xxxxxxx",
         "xxxxxxx",
         "xxxxxxx"
      ],
      "pass":[
         "password",
         "xxxxxxx",
         "xxxxxxx",
         "xxxxxxx",
         "xxxxxxx"
      ],
      "timeout":12000
   },
```
On boot, the esp will test the ssid's. if no connection to one of the five is possible, he will create acces point...

**Comment by CazYokoyama** [comment]
@roema Correction.
If you want to accept multiple APs. I'll make a patch.
----
If you want to accept multiple APs. I'll make a patch which simplify the code by WiFiMulti().

**Comment by roema** [comment]
Hey @CazYokoyama !

Yes, if you have time!

**Comment by CazYokoyama** [comment]
https://github.com/roema/Open-Glider-Network-Groundstation/pull/29

**Comment by CazYokoyama** [comment]
https://github.com/roema/Open-Glider-Network-Groundstation/pull/29

**Comment by roema** [comment]
Hi @CazYokoyama !

Thanks a lot! I will test this weekend!
 Kind regards, manu

**Comment by roema** [comment]
#29 Thanks Caz
