### ISSUE TITLE
No data from GPS even when fix led blinking

### ISSUE THREAD

**Issue by dziedzic99** [roema/Open-Glider-Network-Groundstation#34]
Note that some of the TTGO T-Beam devices come with GPS module preprogrammed in a way that will not work with this software.
**What fixed it for me:** set board in Serial Passthrough mode between Serial and Serial1, both at 9600 baudrate. Then use `ubxtool -p RESET -f /dev/YOURSERIALPORT` to reset GPS to default settings. Afterwards flash this software and it will work.

Suggested fix in the software: add GPS module reset command at boot.

**Comment by schenlap** [comment]
Same problem here. After `ubxtool -p RESET -f /dev/YOURSERIALPORT` the red led ist not flashing any more.
`GNSS_version()` returns `GNSS_MODULE_NONE` on TTGO T-Beam T22 V1.0 (GPS TX=IO34, RX=IO12).

**Comment by dziedzic99** [comment]
Try resetting it again? It took a few tries for mine to catch up.

**Comment by roema** [comment]
Sorry for the late answer, i am very busy at the moment.
Thanks for information, i will try to fix for next version!

I think next weekend i am ready to publish new version.
