### ISSUE TITLE
Why EEPROM.h is removed on v0.0.12?

### ISSUE THREAD

**Issue by CazYokoyama** [roema/Open-Glider-Network-Groundstation#7]
Since v0.0.12, ognbase is not buildable because of missing EEPROM.h. Why? In where you expect to find EEPROM.h?

**Comment by roema** [comment]
I have not removed the EEPROM.h. A couple of libraries have been updated. Please try again. I've updated everything now.

roema

**Comment by CazYokoyama** [comment]
You are correct. When I find a lot of lines in EEPROM.h are deleted, I thought it is removed. Reality is that its many lines are updated. Will close.

There is building error since the next commit of v0.0.12. Will create another issue.
