### ISSUE TITLE
missing submodule information of libraries/ErriezCRC32

### ISSUE THREAD

**Issue by CazYokoyama** [roema/Open-Glider-Network-Groundstation#8]
The submodule, libraries/ErriezCRC32 is introduced on dc203e96ea1338e2c99f610216b3996c161ed4f7, but there is no submodule information, i.e. .gitmodules.

**Comment by roema** [comment]
Thanks for the note! I have added the lib as submodule!

**Comment by CazYokoyama** [comment]
Thx. 1acf6e55eea238f718ff220d72fdcd6b2da7aab9 is buildable.
